// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ecoflow.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []*Header              `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMessage) Reset() {
	*x = HeaderMessage{}
	mi := &file_ecoflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMessage) ProtoMessage() {}

func (x *HeaderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ecoflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMessage.ProtoReflect.Descriptor instead.
func (*HeaderMessage) Descriptor() ([]byte, []int) {
	return file_ecoflow_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderMessage) GetHeader() []*Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pdata         []byte                 `protobuf:"bytes,1,opt,name=pdata,proto3" json:"pdata,omitempty"`                               // Device data (may be encrypted)
	Src           int32                  `protobuf:"varint,2,opt,name=src,proto3" json:"src,omitempty"`                                  // Source
	Dest          int32                  `protobuf:"varint,3,opt,name=dest,proto3" json:"dest,omitempty"`                                // Destination
	DSrc          int32                  `protobuf:"varint,4,opt,name=d_src,json=dSrc,proto3" json:"d_src,omitempty"`                    // Device source
	DDest         int32                  `protobuf:"varint,5,opt,name=d_dest,json=dDest,proto3" json:"d_dest,omitempty"`                 // Device destination
	EncType       int32                  `protobuf:"varint,6,opt,name=enc_type,json=encType,proto3" json:"enc_type,omitempty"`           // 0=none, 1=XOR encrypted
	CheckType     int32                  `protobuf:"varint,7,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`     // Checksum type
	CmdFunc       int32                  `protobuf:"varint,8,opt,name=cmd_func,json=cmdFunc,proto3" json:"cmd_func,omitempty"`           // Command function ID
	CmdId         int32                  `protobuf:"varint,9,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`                 // Command ID
	DataLen       int32                  `protobuf:"varint,10,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`          // Data length
	NeedAck       int32                  `protobuf:"varint,11,opt,name=need_ack,json=needAck,proto3" json:"need_ack,omitempty"`          // Needs acknowledgment
	IsAck         int32                  `protobuf:"varint,12,opt,name=is_ack,json=isAck,proto3" json:"is_ack,omitempty"`                // Is acknowledgment
	AckType       int32                  `protobuf:"varint,13,opt,name=ack_type,json=ackType,proto3" json:"ack_type,omitempty"`          // Acknowledgment type
	Seq           int32                  `protobuf:"varint,14,opt,name=seq,proto3" json:"seq,omitempty"`                                 // Sequence number (used for XOR key)
	ProductId     int32                  `protobuf:"varint,15,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`    // Product ID
	Version       int32                  `protobuf:"varint,16,opt,name=version,proto3" json:"version,omitempty"`                         // Version
	PayloadVer    int32                  `protobuf:"varint,17,opt,name=payload_ver,json=payloadVer,proto3" json:"payload_ver,omitempty"` // Payload version
	TimeSnap      int32                  `protobuf:"varint,18,opt,name=time_snap,json=timeSnap,proto3" json:"time_snap,omitempty"`       // Timestamp
	IsRwCmd       int32                  `protobuf:"varint,19,opt,name=is_rw_cmd,json=isRwCmd,proto3" json:"is_rw_cmd,omitempty"`        // Is read/write command
	IsQueue       int32                  `protobuf:"varint,20,opt,name=is_queue,json=isQueue,proto3" json:"is_queue,omitempty"`          // Is queued
	AckSeq        int32                  `protobuf:"varint,21,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`             // Acknowledgment sequence
	CodeType      int32                  `protobuf:"varint,22,opt,name=code_type,json=codeType,proto3" json:"code_type,omitempty"`       // Code type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_ecoflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_ecoflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_ecoflow_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetPdata() []byte {
	if x != nil {
		return x.Pdata
	}
	return nil
}

func (x *Header) GetSrc() int32 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Header) GetDest() int32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *Header) GetDSrc() int32 {
	if x != nil {
		return x.DSrc
	}
	return 0
}

func (x *Header) GetDDest() int32 {
	if x != nil {
		return x.DDest
	}
	return 0
}

func (x *Header) GetEncType() int32 {
	if x != nil {
		return x.EncType
	}
	return 0
}

func (x *Header) GetCheckType() int32 {
	if x != nil {
		return x.CheckType
	}
	return 0
}

func (x *Header) GetCmdFunc() int32 {
	if x != nil {
		return x.CmdFunc
	}
	return 0
}

func (x *Header) GetCmdId() int32 {
	if x != nil {
		return x.CmdId
	}
	return 0
}

func (x *Header) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *Header) GetNeedAck() int32 {
	if x != nil {
		return x.NeedAck
	}
	return 0
}

func (x *Header) GetIsAck() int32 {
	if x != nil {
		return x.IsAck
	}
	return 0
}

func (x *Header) GetAckType() int32 {
	if x != nil {
		return x.AckType
	}
	return 0
}

func (x *Header) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Header) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetPayloadVer() int32 {
	if x != nil {
		return x.PayloadVer
	}
	return 0
}

func (x *Header) GetTimeSnap() int32 {
	if x != nil {
		return x.TimeSnap
	}
	return 0
}

func (x *Header) GetIsRwCmd() int32 {
	if x != nil {
		return x.IsRwCmd
	}
	return 0
}

func (x *Header) GetIsQueue() int32 {
	if x != nil {
		return x.IsQueue
	}
	return 0
}

func (x *Header) GetAckSeq() int32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Header) GetCodeType() int32 {
	if x != nil {
		return x.CodeType
	}
	return 0
}

var File_ecoflow_proto protoreflect.FileDescriptor

const file_ecoflow_proto_rawDesc = "" +
	"\n" +
	"\recoflow.proto\x12\aecoflow\"8\n" +
	"\rHeaderMessage\x12'\n" +
	"\x06header\x18\x01 \x03(\v2\x0f.ecoflow.HeaderR\x06header\"\xba\x04\n" +
	"\x06Header\x12\x14\n" +
	"\x05pdata\x18\x01 \x01(\fR\x05pdata\x12\x10\n" +
	"\x03src\x18\x02 \x01(\x05R\x03src\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\x05R\x04dest\x12\x13\n" +
	"\x05d_src\x18\x04 \x01(\x05R\x04dSrc\x12\x15\n" +
	"\x06d_dest\x18\x05 \x01(\x05R\x05dDest\x12\x19\n" +
	"\benc_type\x18\x06 \x01(\x05R\aencType\x12\x1d\n" +
	"\n" +
	"check_type\x18\a \x01(\x05R\tcheckType\x12\x19\n" +
	"\bcmd_func\x18\b \x01(\x05R\acmdFunc\x12\x15\n" +
	"\x06cmd_id\x18\t \x01(\x05R\x05cmdId\x12\x19\n" +
	"\bdata_len\x18\n" +
	" \x01(\x05R\adataLen\x12\x19\n" +
	"\bneed_ack\x18\v \x01(\x05R\aneedAck\x12\x15\n" +
	"\x06is_ack\x18\f \x01(\x05R\x05isAck\x12\x19\n" +
	"\back_type\x18\r \x01(\x05R\aackType\x12\x10\n" +
	"\x03seq\x18\x0e \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x0f \x01(\x05R\tproductId\x12\x18\n" +
	"\aversion\x18\x10 \x01(\x05R\aversion\x12\x1f\n" +
	"\vpayload_ver\x18\x11 \x01(\x05R\n" +
	"payloadVer\x12\x1b\n" +
	"\ttime_snap\x18\x12 \x01(\x05R\btimeSnap\x12\x1a\n" +
	"\tis_rw_cmd\x18\x13 \x01(\x05R\aisRwCmd\x12\x19\n" +
	"\bis_queue\x18\x14 \x01(\x05R\aisQueue\x12\x17\n" +
	"\aack_seq\x18\x15 \x01(\x05R\x06ackSeq\x12\x1b\n" +
	"\tcode_type\x18\x16 \x01(\x05R\bcodeTypeB9Z7github.com/tess1o/go-ecoflow-exporter/internal/protobufb\x06proto3"

var (
	file_ecoflow_proto_rawDescOnce sync.Once
	file_ecoflow_proto_rawDescData []byte
)

func file_ecoflow_proto_rawDescGZIP() []byte {
	file_ecoflow_proto_rawDescOnce.Do(func() {
		file_ecoflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecoflow_proto_rawDesc), len(file_ecoflow_proto_rawDesc)))
	})
	return file_ecoflow_proto_rawDescData
}

var file_ecoflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ecoflow_proto_goTypes = []any{
	(*HeaderMessage)(nil), // 0: ecoflow.HeaderMessage
	(*Header)(nil),        // 1: ecoflow.Header
}
var file_ecoflow_proto_depIdxs = []int32{
	1, // 0: ecoflow.HeaderMessage.header:type_name -> ecoflow.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ecoflow_proto_init() }
func file_ecoflow_proto_init() {
	if File_ecoflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecoflow_proto_rawDesc), len(file_ecoflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ecoflow_proto_goTypes,
		DependencyIndexes: file_ecoflow_proto_depIdxs,
		MessageInfos:      file_ecoflow_proto_msgTypes,
	}.Build()
	File_ecoflow_proto = out.File
	file_ecoflow_proto_goTypes = nil
	file_ecoflow_proto_depIdxs = nil
}
