services:
  go_ecoflow_exporter:
    build:
      context: ./..
      dockerfile: ./Dockerfile
    container_name: go_ecoflow_exporter
    ports:
      - 2112:2112
    restart: unless-stopped
    environment:
      EXPORTER_TYPE: ${EXPORTER_TYPE}
      ECOFLOW_ACCESS_KEY: ${ECOFLOW_ACCESS_KEY}
      ECOFLOW_SECRET_KEY: ${ECOFLOW_SECRET_KEY}
      ECOFLOW_EMAIL: ${ECOFLOW_EMAIL}
      ECOFLOW_PASSWORD: ${ECOFLOW_PASSWORD}
      ECOFLOW_DEVICES: ${ECOFLOW_DEVICES}
      ECOFLOW_DEVICES_PRETTY_NAMES: ${ECOFLOW_DEVICES_PRETTY_NAMES}
      MQTT_DEVICE_OFFLINE_THRESHOLD_SECONDS: ${MQTT_DEVICE_OFFLINE_THRESHOLD_SECONDS}
      PROMETHEUS_ENABLED: ${PROMETHEUS_ENABLED}
      METRIC_PREFIX: ${METRIC_PREFIX}
      TIMESCALE_ENABLED: ${TIMESCALE_ENABLED}
      TIMESCALE_URL: ${TIMESCALE_URL}
      REDIS_ENABLED: ${REDIS_ENABLED}
      REDIS_URL: ${REDIS_URL}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}