version: '3.8'

services:
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis-timeseries
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--loadmodule", "/usr/lib/redis/modules/redistimeseries.so"]
    ports:
      - "6379:6379"

volumes:
  redis_data:
    driver: local