// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package timescaledb

import (
	"time"
)

type EcoflowMetric struct {
	Timestamp    time.Time `json:"timestamp"`
	SerialNumber string    `json:"serial_number"`
	Metrics      []byte    `json:"metrics"`
}
