// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package timescaledb

import (
	"context"
)

type Querier interface {
	GetMetricsByDevice(ctx context.Context, serialNumber string) ([]EcoflowMetric, error)
	InsertMetric(ctx context.Context, arg InsertMetricParams) (EcoflowMetric, error)
}

var _ Querier = (*Queries)(nil)
